<?php

namespace Page\PageBundle\Repository;

/**
 * pageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pageRepository extends \Doctrine\ORM\EntityRepository
{
}
